language: php
dist: focal

branches:
  only:
    - master
    - /^\d+\.\d+\.(?:\d+|x)/

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - os: linux
      dist: bionic
      php: 7.2
      services: mysql
      env: DB=mysql
    - os: linux
      dist: bionic
      php: 7.2
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - os: linux
      dist: bionic
      php: 7.2
      addons:
        postgresql: 11
      env: DB=postgresql
    - os: linux
      dist: bionic
      php: 7.3
      services: mysql
      env: DB=mysql
    - os: linux
      dist: bionic
      php: 7.3
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - os: linux
      dist: bionic
      php: 7.3
      addons:
        postgresql: 11
      env: DB=postgresql
    - php: 7.4
      services: mysql
      env: DB=mysql
    - php: 7.4
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - os: linux
      dist: bionic
      php: 7.4
      addons:
        postgresql: 11
      env: DB=postgresql
    - php: 8.0snapshot
      services: mysql
      env: DB=mysql
    - php: 8.0snapshot
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - os: linux
      dist: bionic
      php: 8.0snapshot
      addons:
        postgresql: 11
      env: DB=postgresql
    - php: nightly
      services: mysql
      env: DB=mysql
    - php: nightly
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - os: linux
      dist: bionic
      php: nightly
      addons:
        postgresql: 11
      env: DB=postgresql
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - chmod +x travis/*.sh

install:
  - source travis/install.sh

before_script:
  - source travis/before_script.sh

script:
  - source travis/script.sh
