language: php
dist: bionic

branches:
  only:
    - master
    - /^\d+\.\d+\.(?:\d+|x)/

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - os: linux
      dist: xenial
      php: 7.0
      services: mysql
      env: DB=mysql
    - os: linux
      dist: xenial
      php: 7.0
      addons:
        mariadb: 10.2
      env: DB=mariadb
    - os: linux
      dist: xenial
      php: 7.0
      addons:
        postgresql: 10
      env: DB=postgresql
    - php: 7.1
      services: mysql
      env: DB=mysql
    - php: 7.1
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - php: 7.1
      addons:
        postgresql: 11
      env: DB=postgresql
    - php: 7.2
      services: mysql
      env: DB=mysql
    - php: 7.2
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - php: 7.2
      addons:
        postgresql: 11
      env: DB=postgresql
    - php: 7.3
      services: mysql
      env: DB=mysql
    - php: 7.3
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - php: 7.3
      addons:
        postgresql: 11
      env: DB=postgresql
    - os: linux
      dist: focal
      php: 7.4
      services: mysql
      env: DB=mysql
    - os: linux
      dist: focal
      php: 7.4
      addons:
        mariadb: 10.3
      env: DB=mariadb
    # TODO: Use Ubuntu Focal Fossa
    - php: 7.4
      addons:
        postgresql: 11
      env: DB=postgresql
    - os: linux
      dist: focal
      php: nightly
      services: mysql
      env: DB=mysql
    - os: linux
      dist: focal
      php: nightly
      addons:
        mariadb: 10.3
      env: DB=mariadb
    - os: linux
      dist: focal
      php: nightly
      services: postgresql
      env: DB=postgresql
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - chmod +x travis/*.sh

install:
  - source travis/install.sh

before_script:
  - source travis/before_script.sh

script:
  - source travis/script.sh
