language: php

addons:
  mariadb: 10.1

matrix:
  include:
    - php: 5.6
      env: DB=mariadb
    - php: 7.0
      env: DB=mariadb
    - php: 7.1
      env: DB=mariadb
  fast_finish: true

branches:
  only:
    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - mysql -u root < travis/schema_test_db.sql
  - mysql -u root < travis/data_test_db.sql

script:
  - vendor/bin/phpunit
