language: php
dist: xenial

branches:
  only:
    - master
    - /^\d+\.\d+\.(?:\d+|x)/

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.0
      addons:
        mariadb: 10.2
      env: DB=mariadb
    - php: 7.0
      addons:
        postgresql: 10
      env: DB=postgresql
    - php: 7.1
      addons:
        mariadb: 10.2
      env: DB=mariadb
    - php: 7.1
      addons:
        postgresql: 10
      env: DB=postgresql
    - php: 7.2
      addons:
        mariadb: 10.2
      env: DB=mariadb
    - php: 7.2
      addons:
        postgresql: 10
      env: DB=postgresql
    - php: 7.3
      addons:
        mariadb: 10.2
      env: DB=mariadb
    - php: 7.3
      addons:
        postgresql: 10
      env: DB=postgresql
    - php: 7.4
      addons:
        mariadb: 10.2
      env: DB=mariadb
    - php: 7.4
      addons:
        postgresql: 10
      env: DB=postgresql
    - php: nightly
      addons:
        mariadb: 10.2
      env: DB=mariadb
    - php: nightly
      addons:
        postgresql: 10
      env: DB=postgresql
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - chmod +x travis/*.sh

install:
  - source travis/install.sh

before_script:
  - source travis/before_script.sh

script:
  - source travis/script.sh
